social_auth_37signals.settings:
  type: config_object
  label: 'Social Auth 37Signals settings'
  mapping:
    client_id:
      type: string
      label: 'Client ID'
    client_secret:
      type: string
      label: 'Client Secret'
